import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage; 
import org.apache.pdfbox.rendering.PDFRenderer;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.io.RandomAccessReadBuffer; 
import java.sql.Blob;


/**
 *
 * @author Lovely
 */
public class table extends javax.swing.JFrame {

    /**
     * Creates new form table
     */
    public table() {
        initComponents();
         studentInfoTable();
         setStudentName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        gradeslip = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tbl_firstname = new javax.swing.JLabel();
        tbl_middleName = new javax.swing.JLabel();
        tbl_lastname = new javax.swing.JLabel();
        tbl_gender = new javax.swing.JLabel();
        tbl_contactNumber = new javax.swing.JLabel();
        tbl_idNumber = new javax.swing.JLabel();
        tbl_units = new javax.swing.JLabel();
        tbl_course = new javax.swing.JLabel();
        tbl_major = new javax.swing.JLabel();
        tbl_section = new javax.swing.JLabel();
        tbl_yearlevel = new javax.swing.JLabel();
        tbl_status = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        student_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Firstname:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setText("Lastname:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Gender:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setText("Contact Number:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel6.setText("No of Units:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setText("Course:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jLabel8.setText("Major:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jLabel9.setText("Section:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel10.setText("Year Level:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel11.setText("Status:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        gradeslip.setText("My Grade Slip >");
        gradeslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeslipActionPerformed(evt);
            }
        });
        jPanel1.add(gradeslip, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel12.setText("Student ID:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        tbl_firstname.setText("dummy text");
        jPanel1.add(tbl_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        tbl_middleName.setText("dummy text");
        jPanel1.add(tbl_middleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        tbl_lastname.setText("dummy text");
        jPanel1.add(tbl_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        tbl_gender.setText("dummy text");
        jPanel1.add(tbl_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        tbl_contactNumber.setText("dummy text");
        jPanel1.add(tbl_contactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        tbl_idNumber.setText("dummy text");
        jPanel1.add(tbl_idNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        tbl_units.setText("dummy text");
        jPanel1.add(tbl_units, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        tbl_course.setText("dummy text");
        jPanel1.add(tbl_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        tbl_major.setText("dummy text");
        jPanel1.add(tbl_major, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        tbl_section.setText("dummy text");
        jPanel1.add(tbl_section, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        tbl_yearlevel.setText("dummy text");
        jPanel1.add(tbl_yearlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        tbl_status.setText("dummy text");
        jPanel1.add(tbl_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel13.setText("Middle Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        student_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        student_name.setText("Student Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(student_name)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(student_name)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     Connection con;
    PreparedStatement ps;
    Login login = new Login();
   
 
    
   private void studentInfoTable() {
       
       String emailAddress = login.studentEmail;

    
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");

        String jdbcURL = "jdbc:mysql://localhost:3306/loginregister?zeroDateTimeBehavior=CONVERT_TO_NULL";
        String db_username = "root";
        String db_password = "";

        con = DriverManager.getConnection(jdbcURL, db_username, db_password);

        ps = con.prepareStatement("SELECT * FROM registration_form_db where email = ?;");
   
        ps.setString(1, emailAddress);
        
       ResultSet rs = ps.executeQuery();
   
        if(rs.next()){
            tbl_firstname.setText(rs.getString("firstname").toUpperCase());
            tbl_middleName.setText(rs.getString("middlename").toUpperCase());
            tbl_lastname.setText(rs.getString("lastname").toUpperCase());
            tbl_gender.setText(rs.getString("gender".toUpperCase()));
            tbl_contactNumber.setText(rs.getString("contact_no").toUpperCase());
            tbl_section.setText(rs.getString("section").toUpperCase());
            tbl_units.setText(rs.getString("no_units").toUpperCase());         
            tbl_idNumber.setText(rs.getString("id_number").toUpperCase());
            tbl_course.setText(rs.getString("course").toUpperCase());
            tbl_major.setText(rs.getString("major").toUpperCase());
            tbl_yearlevel.setText(rs.getString("yearlevel").toUpperCase());
            tbl_status.setText(rs.getString("status").toUpperCase());
        }
        else{
            JOptionPane.showMessageDialog(this, "No Information Found!");
        }
            

            
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(table.class.getName()).log(Level.SEVERE, null, ex);
    }
}

      public static void setStudentName(){
        Login login = new Login();
        String setStudentFirstname = login.firstname;
        String setStudentLastname = login.lastname;

       student_name.setText("HELLO "+setStudentFirstname.toUpperCase() +" "+ setStudentLastname.toUpperCase()+"!");
       
    }
      
    private void displayPDF(byte[] pdfData) {
    try {
        File tempFile = File.createTempFile("temp_pdf", ".pdf");
        try (OutputStream os = new FileOutputStream(tempFile)) {
            os.write(pdfData);
        }

        Desktop.getDesktop().open(tempFile);

    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error displaying PDF: " + e.getMessage());
    }
}

private byte[] fetchPDFDataFromDatabase() {
    String setStudentFirstname = login.firstname;
    String setStudentLastname = login.lastname;

    byte[] pdfData = null;

    try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/loginregister?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
         PreparedStatement statement = connection.prepareStatement("SELECT gradeslip FROM registration_form_db WHERE firstname = ? AND lastname = ?")) {

        statement.setString(1, setStudentFirstname);
        statement.setString(2, setStudentLastname);

        try (ResultSet resultSet = statement.executeQuery()) {
            if (resultSet.next()) {
                Blob blob = resultSet.getBlob("gradeslip");
                pdfData = blob.getBytes(1, (int) blob.length());
            }
        }
    } catch (SQLException ex) {
        // Log the exception or handle it appropriately
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error fetching PDF data from database: " + ex.getMessage());
    }

    return pdfData;
}

    private void gradeslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeslipActionPerformed
        byte[] pdfData = fetchPDFDataFromDatabase();
            displayPDF(pdfData);
    }//GEN-LAST:event_gradeslipActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gradeslip;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel student_name;
    private javax.swing.JLabel tbl_contactNumber;
    private javax.swing.JLabel tbl_course;
    private javax.swing.JLabel tbl_firstname;
    private javax.swing.JLabel tbl_gender;
    private javax.swing.JLabel tbl_idNumber;
    private javax.swing.JLabel tbl_lastname;
    private javax.swing.JLabel tbl_major;
    private javax.swing.JLabel tbl_middleName;
    private javax.swing.JLabel tbl_section;
    private javax.swing.JLabel tbl_status;
    private javax.swing.JLabel tbl_units;
    private javax.swing.JLabel tbl_yearlevel;
    // End of variables declaration//GEN-END:variables
}
